# Generated by Django 4.2 on 2025-07-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品説明')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格')),
                ('stock', models.IntegerField(default=0, verbose_name='在庫数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsite.category', verbose_name='ジャンル')),
            ],
        ),
    ]
