# Generated by Django 4.2 on 2025-07-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0003_article_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
