# Generated by Django 4.2 on 2025-07-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0006_purchasehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
